#etxattr_getxattr runs setxattr with 1 name/value pair and runs getxattr.  The getxattr returns and error due to a hash mismatch.  This error also exists in the legacy tests
---

- name: setup_touch_setxattr_getxattr
  type: setup
  tmpdirs:
    - name: 031_touch_setxattr_getxattr
      varname: config_dir
  randnames:
    - test_volume
    - attr_ug
    - attr_file
    - attrn
    - test_rg
  vars:
    - name: syndicate_conf
      value: $config_dir/syndicate.conf
    - name: rg_driver
      value: $SYNDICATE_PYTHON_ROOT/syndicate/rg/drivers/disk
    - name: rg_path
      value: $SYNDICATE_RG_ROOT/syndicate-rg
    - name: put_path
      value: $SYNDICATE_UG_ROOT/syndicate-put
    - name: cat_path
      value: $SYNDICATE_UG_ROOT/syndicate-cat
    - name: getxattr_path
      value: $SYNDICATE_UG_ROOT/syndicate-getxattr
    - name: setxattr_path
      value: $SYNDICATE_UG_ROOT/syndicate-setxattr
    - name: stat_path
      value: $SYNDICATE_UG_ROOT/syndicate-stat
    - name: touch_path
      value: $SYNDICATE_UG_ROOT/syndicate-touch
    - name: unlink_path
      value: $SYNDICATE_UG_ROOT/syndicate-unlink
  debug: verbose stderr

- name: config
  type: sequential
  tasks:
    - name: setup
      command: $SYNDICATE_TOOL --trust_public_key -c "$syndicate_conf" --debug setup "$SYNDICATE_ADMIN" "$SYNDICATE_PRIVKEY_PATH" "$SYNDICATE_MS"

    - name: add test volume
      command: $SYNDICATE_TOOL -c "$syndicate_conf" create_volume name=$test_volume description="test volume" blocksize=4096 email=$SYNDICATE_ADMIN
    
    - name: create RG
      command: $SYNDICATE_TOOL -c "$syndicate_conf" create_gateway name=$test_rg type=RG volume=$test_volume email=$SYNDICATE_ADMIN private_key=auto port=31112

    - name: update RG
      command: $SYNDICATE_TOOL -c "$syndicate_conf" update_gateway name=$test_rg caps=ALL port=31112 driver=$rg_driver

- name: daemon RG
  type: daemon
  tasks:
    - name: start RG
      command: $rg_path -c "$syndicate_conf" -d2 -f -u $SYNDICATE_ADMIN -v $test_volume -g $test_rg
      exit: 0

- name: check syndicate is mounted
  type: sequential
  tasks:
    - name: wait for RG to be online
      command: $tasksf_dir/waitgateway.py localhost 31112 20
      exit: 0

- name: setup UGs
  type: sequential
  tasks:
    - name: create attr UG
      command: $SYNDICATE_TOOL -c "$syndicate_conf" create_gateway name=$attr_ug type=UG volume=$test_volume email=$SYNDICATE_ADMIN private_key=auto port=31113

    - name: update attr UG
      command: $SYNDICATE_TOOL -c "$syndicate_conf" update_gateway name=$attr_ug caps=ALL

- name: test touch file
  type: sequential
  tasks:
    - name: touch file
      command: $touch_path -d2 -f -c "$syndicate_conf" -u $SYNDICATE_ADMIN -v $test_volume -g $attr_ug /$attr_file

- name: run setxattr tests
  type: sequential
  tasks:
    - name: setxattr
      command: $setxattr_path -d2 -f -c "$syndicate_conf" -u $SYNDICATE_ADMIN -v $test_volume -g $attr_ug /$attr_file ${attrn}-name ${attrn}-value

- name: run getxattr tests
  type: sequential
  tasks:
    - name: getxattr
      command: $getxattr_path -d2 -f -c "$syndicate_conf" -u $SYNDICATE_ADMIN -v $test_volume -g $attr_ug /$attr_file ${attrn}-name
      containserr: ${attrn}-value

- name: clean up
  type: sequential
  tasks:
    - name: unlink files
      command: $unlink_path -d2 -f -c "$syndicate_conf" -u $SYNDICATE_ADMIN -v $test_volume -g $attr_ug /$attr_file

    - name: delete volume
      command: $SYNDICATE_TOOL -c "$syndicate_conf" delete_volume "$test_volume"
